// Shared domain types for GridPath. These mirror §8 of the PRD.

export type GridPointType = "line" | "minor_line" | "pole" | "transformer" | "substation";

export type ServiceMode = "overhead" | "underground";

/**
 * How the property reaches the grid.
 * - "house": connect directly at the existing pole/meter — no wire run needed.
 * - "standard": run a new service line to the property (distance-based cost).
 */
export type WireScenario = "house" | "standard";

export type PropertyType = "new_build" | "land" | "adu" | "load_upgrade";

export interface LatLon {
  lat: number;
  lon: number;
}

/** A single power feature returned from Overpass, normalized for the map. */
export interface PowerFeature {
  id: string;
  type: GridPointType;
  /** Node features have a single point; way features have an ordered path. */
  geometry: LatLon[];
}

export interface CostBreakdown {
  baseConnectionFee: number;
  lineExtension: number;
  transformer: number;
  meterServiceDrop: number;
}

export interface EstimatedCost {
  total: number;
  breakdown: CostBreakdown;
}

export interface EstimatedTimeline {
  min: number;
  max: number;
  unit: "weeks" | "months";
  /** Plain-language label, e.g. "6–12 weeks". */
  label: string;
  /** Flat application/review note shown as subtext, e.g. "+2 weeks application & review". */
  applicationNote: string;
}

export interface ConnectionEstimate {
  id: string;
  address: string;
  coordinates: LatLon;
  nearestGridPoint: LatLon & { type: GridPointType };
  distanceFeet: number;
  needsTransformer: boolean;
  mode: ServiceMode;
  /** Whether a new line run is needed ("standard") or the property connects at the pole ("house"). */
  wireScenario: WireScenario;
  estimatedCost: EstimatedCost;
  estimatedTimeline: EstimatedTimeline;
  /** One-line, human-readable explanation of how the numbers were derived. */
  explanation: string;
  /** Nearby power features for the optional map overlay. */
  features: PowerFeature[];
  /** True when results came from the bundled fallback fixture, not live Overpass. */
  fromFixture: boolean;
}

export interface ApplicationLead {
  estimateId: string;
  name: string;
  email: string;
  phone: string;
  propertyType: PropertyType;
  submittedAt: string;
}

export interface GeocodeResult {
  label: string;
  lat: number;
  lon: number;
}

// ---- Grants & offer ----

/** A single grant/rebate that can be applied against the connection cost. */
export interface Grant {
  id: string;
  name: string;
  /** Issuing body, e.g. "USDA Rural Energy for America". */
  authority: string;
  /** One-line plain-language description. */
  detail: string;
  /** Face value in USD. */
  amount: number;
}

/** The connection "offer" with grants applied to reach a much cheaper net cost. */
export interface GrantOffer {
  /** The full connection cost before assistance — the "offer". */
  gross: number;
  grants: Grant[];
  /** Total assistance actually applied (capped so you always pay something). */
  totalApplied: number;
  /** Net cost after grants. */
  net: number;
  /** Percent saved vs the gross offer. */
  percentOff: number;
}

// ---- Clean-energy advisor ----

/** Grounding data about a property's clean-energy potential (real or dummy). */
export interface PropertySignals {
  address: string;
  region: string;
  /** Usable rooftop area for solar, sq ft. */
  roofAreaSqFt: number;
  /** Max number of standard panels that fit. */
  maxPanels: number;
  /** Peak sun hours per year. */
  sunHoursPerYear: number;
  /** Estimated annual solar production potential, kWh. */
  solarPotentialKwh: number;
  /** Local utility electricity rate, $/kWh. */
  utilityRate: number;
  /** Estimated current annual household electricity use, kWh. */
  annualUsageKwh: number;
  /** Estimated current annual electricity bill, USD. */
  annualBill: number;
  /** Grid carbon intensity, kg CO2 per kWh. */
  gridCarbonKgPerKwh: number;
  /** True when rooftop figures came from the Google Solar API, not estimates. */
  fromSolarApi: boolean;
}

export interface CleanEnergyOption {
  key: string;
  name: string;
  icon: string;
  recommended: boolean;
  headline: string;
  whatItIs: string;
  estimatedCost: number;
  annualSavings: number;
  paybackYears: number;
  co2ReductionTons: number;
  incentives: string[];
  priority: number;
}

export interface CleanEnergyPlan {
  headline: string;
  summary: string;
  cleanScoreBefore: number;
  cleanScoreAfter: number;
  options: CleanEnergyOption[];
  recommendedBundle: {
    items: string[];
    totalCost: number;
    totalAnnualSavings: number;
    note: string;
  };
  /** "claude" when generated by the model, "fallback" when computed locally. */
  source: "claude" | "fallback";
  signals: PropertySignals;
}
